version: '3.7'

services:
    php-apache:
      restart: always
      ports:
        - 8000:80
      environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
      build:
        context: .
        dockerfile: ./docker/php-apache/Dockerfile
      volumes:
        - ./:/var/www/html
        - ./docker/php-apache/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./docker/php-apache/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      depends_on:
        - mysql

    mysql:
      build: ./docker/mysql
      restart: always
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
      hostname: mysql
      volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./docker/mysql/dump:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: main
        MYSQL_USER: kit-starter
        MYSQL_PASSWORD: kit-starter

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8080:80
      links:
        - mysql