version: '3.7'

services:
    php-apache:
      container_name: kit-starter-api-platform-symfony5-lamp-docker_php-apache
      restart: always
      ports:
        - 8000:80
      environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
      build:
        context: .
        dockerfile: ./docker/php-apache/Dockerfile
      volumes:
        - ./:/var/www/html
        - ./docker/php-apache/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./docker/php-apache/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      depends_on:
        - mysql

    mysql:
      image: mysql
      command: "--default-authentication-plugin=mysql_native_password"
      container_name: kit-starter-api-platform-symfony5-lamp-docker_mysql
      volumes:
        - ./docker/mysql/conf:/etc/mysql/conf.d
        - mysql_data:/var/lib/mysql
        - ./docker/mysql/dump:/docker-entrypoint-initdb.d

      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: kit-starter
        MYSQL_USER: kit-starter
        MYSQL_PASSWORD: kit-starter

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: kit-starter-api-platform-symfony5-lamp-docker_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8080:80
      links:
        - mysql

volumes:
  mysql_data: { driver: local }
